const encodedChannelData = {
    1: "HER7VlgbBVIUBmE1O0UNFlBeFRNFRV1IFwpeWFJQQUsUSFtSUhsCGRQZTQgcAhlVHRgPHRpFDB4VFUdZRUUeV0kLRlMUXkMVIyB5LBceRBRIFhpFDAAFAg0FVgQGVwNeUAUOVFRDBwBRQQRTR1BSBEIGUVcXDEdFDVVUVAMIBl5RUlcDAkAFAwVFUVAWAQ9URwJRAgUFUgMaG0o=",
    2: "HER7VlgbBVIUBmE1O0UNFlBeFRNFRV1IFwpeWFJQQUsUSFtSUhsCGRQZTQgcAhlVHRgPHRpFDB4VFUdZRUUeVEkLRlMUXkMVIyB5LBceRBRIFhpFUFBeVwEHVFVSAFVTVAADU1RAAgYEFlUBFlVSD0IGUVcXDEdFWQRWBwUHCgJRXgNRAkVXUQUWUAFLUFRTQFRVUlYBVVIaG0o=",
    3: "HER7VlgbBVIUBmE1O0UNFlBeFRNFRV1IFwpeWFJQQUsUSFtSUhsCGRQZTQgcAhlVHRgPHRpFDB4VFUdZRUUeVUkLRlMUXkMVIyB5LBceRBRIFhpFAg9SUgsCUgUDAgFXAVcHDgFAAgBVEAUCQVMBBEIGUVcXDEdFDgAGBQNTAlYBA1IEAkcADwUXBl4TBQNUQQdZBFADV1UaG0o=",
    4: "",
    5: "",
    6: "",
    7: "",
    8: "",
    9: ""
};
